#pragma once

#include <stdbool.h>

// drivers/crowbar_mosfet — voltage-glitching crowbar path selector.
//
// v2.x exposes two possible glitch paths; software chooses one by
// driving the corresponding gate HIGH:
//   * LP (GP16) — low-power shorting path (auxiliary crowbar / bleed)
//   * HP (GP17) — main N-MOSFET (IRLML0060) — the real voltage glitch
//
// There is NO hardware multiplexer on v2.2 — the driver just asserts
// or de-asserts each gate pin. HV is applied elsewhere
// (hv_charger + the DC rail into the MOSFET drain); this driver
// only picks which path is live.
//
// SAFETY CONTRACT: at most one path is ever HIGH simultaneously. The
// driver enforces this with break-before-make transitions (the
// outgoing gate drops LOW before the incoming gate goes HIGH). Idle
// is both LOW.
//
// NOTE: This driver does NOT implement the sub-µs pulse itself.
// The glitch fire waveform (trigger-delay-glitch-verify) is PIO
// generated by the glitch_engine service in F5 and drives the gate
// from PIO, bypassing this driver's set_path API for the fire
// phase. That is why the pulse test is deferred to F5, not F2.

typedef enum {
    CROWBAR_PATH_NONE = 0,  // both gates LOW — idle / safe
    CROWBAR_PATH_LP   = 1,  // low-power path
    CROWBAR_PATH_HP   = 2,  // high-power path (N-MOSFET)
} crowbar_path_t;

// Configure GP16 and GP17 as outputs, both LOW. Must be called
// before any other function. Safe to call more than once.
void crowbar_mosfet_init(void);

// Select which path (if any) is active. Break-before-make: if
// switching between LP and HP, the outgoing gate is driven LOW in
// the same call BEFORE the new gate is driven HIGH. Out-of-range
// values are treated as CROWBAR_PATH_NONE.
void crowbar_mosfet_set_path(crowbar_path_t path);

// Return the last path set. Shadow state — not a pin read.
crowbar_path_t crowbar_mosfet_get_path(void);
